routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::group(['middleware' => 'auth'], function () {
	Route::get('/', array( 'as' => 'index', 'uses' => 'ArtistController@index' ) );
	Route::get('/home', array( 'as' => 'home', 'uses' => 'ArtistController@index' ) );

// Artist
	Route::model('artist', 'App\Models\Artist');
	Route::resource('artist', 'ArtistController');
	Route::get( '/artist/{artist}/delete', array( 'as' => 'artist.delete', 'uses' => 'ArtistController@delete' ) );

// Album
	Route::model('album', 'App\Models\Album');
	Route::resource('album', 'AlbumController');
	Route::get( '/album/{album}/delete', array( 'as' => 'album.delete', 'uses' => 'AlbumController@delete' ) );
	Route::post( '/album/save-order', array( 'as' => 'album.save-order', 'uses' => 'AlbumController@save_order' ) );

// Release
	Route::model('release', 'App\Models\Release');
	Route::resource('release', 'ReleaseController');
	Route::get( '/release/{release}/delete', array( 'as' => 'release.delete', 'uses' => 'ReleaseController@delete' ) );
	Route::get( '/release/{release}/export-id3', array( 'as' => 'release.export-id3', 'uses' => 'ReleaseController@export_id3' ) );
	Route::post( '/release/generate-catalog-num', array( 'as' => 'release.catalog-num', 'uses' => 'ReleaseController@generate_catalog_num' ) );

// Tracks
	Route::model('track', 'App\Models\Track');
	Route::get( '/track/{track}/delete', array( 'as' => 'track.delete', 'uses' => 'TrackController@delete' ) );
	Route::post( '/track/save-order', array( 'as' => 'track.save-order', 'uses' => 'TrackController@save_order' ) );
	Route::resource('track', 'TrackController');

// Audio
	Route::model('audio', 'App\Models\Audio');
	Route::get( '/audio/{audio}/delete/', array( 'as' => 'audio.delete', 'uses' => 'AudioController@delete' ) );
	Route::resource('audio', 'AudioController');

// Ecommerce
	Route::model('ecommerce', 'App\Models\Ecommerce');
	Route::get( '/ecommerce/{ecommerce}/delete', array( 'as' => 'ecommerce.delete', 'uses' => 'EcommerceController@delete' ) );
	Route::post( '/ecommerce/save-order', array( 'as' => 'ecommerce.save-order', 'uses' => 'EcommerceController@save_order' ) );
	Route::resource('ecommerce', 'EcommerceController');

// Songs
	Route::model('song', 'App\Models\Song');
	Route::get( '/song/{song}/delete', array( 'as' => 'song.delete', 'uses' => 'SongController@delete' ) );
	Route::get( '/song/{song}/lyrics', array( 'as' => 'song.lyrics', 'uses' => 'SongController@lyrics' ) );
	Route::resource('song', 'SongController');

// Recordings
	Route::model('recording', 'App\Models\Recording');
	Route::get( '/recording/{recording}/delete', array( 'as' => 'recording.delete', 'uses' => 'RecordingController@delete' ) );
	Route::post( '/recording/generate-isrc', array( 'as' => 'recording.isrc', 'uses' => 'RecordingController@generate_isrc' ) );
	Route::resource('recording', 'RecordingController');

// Profile
	Route::model('user', 'App\Models\User');
	Route::resource('user', 'UserController');
	Route::get( '/user/{user}/delete', array( 'as' => 'user.delete', 'uses' => 'UserController@delete' ) );
});

Auth::routes();

app/Models/Release.php
<?php
/**
 * Created by PhpStorm.
 * User: gregbueno
 * Date: 5/26/14
 * Time: 5:31 PM
 */

namespace App\Models;

use Illuminate\Support\Facades\DB;

use Illuminate\Database\Eloquent\Model;

class Release extends Model {

	protected $table = 'ep4_albums_releases';
	protected $primaryKey = 'release_id';
	protected $softDelete = true;
	protected $fillable = array(
		'release_album_id',
        'release_artist_display_name',
		'release_upc_num',
		'release_catalog_num',
		'release_format_id',
		'release_alternate_title',
		'release_alias',
		'release_label',
		'release_release_date',
		'release_image',
		'release_is_visible',
	);
	protected $guarded = array(
		'release_id',
		'release_date_modified',
		'release_deleted',
	);
	private $_catalog_stem;

	public function album() {
		return $this->belongsTo('App\Models\Album', 'release_album_id', 'album_id');
	}

	public function tracks() {
		return $this->hasMany('App\Models\Track', 'track_release_id', 'release_id')->orderBy('track_disc_num')->orderBy('track_track_num');
	}

	public function format() {
		return $this->hasOne('App\Models\ReleaseFormat', 'format_id', 'release_format_id');
	}

	public function ecommerce() {
		return $this->hasMany('App\Models\Ecommerce', 'ecommerce_release_id', 'release_id')->orderBy('ecommerce_list_order');
	}

	public function generate_catalog_num() {
		$catalog_num = null;

		// Get the most recently generated code for the year.
		$result = $this->_retrieve_last_number();

		// If a result exists, increment the designation code.
		if (!empty($result)) {
			list ($stem, $suffix) = explode('-', $result->release_catalog_num);
			$new_suffix = intval( substr($suffix, 0, 3) );
			$new_suffix++;
			$catalog_num = $stem . '-' . sprintf('%03d', $new_suffix) . 'B';
		} else {
			// If no result exists, create the first code.
			$catalog_num = $this->_catalog_stem . sprintf('%03d', 1) . 'B';
		}

		// Return the code.
		return $catalog_num;
	}

	public function get_cdn_image($size = '') {
        $catalog_num = strtolower($this->release_catalog_num);
        $cdn = 'https:' . OBSERVANTRECORDS_CDN_BASE_URI;
        $_size = (!empty($size)) ? '_' . $size : null;
        $release_image = <<< RELEASE_IMAGE
{$cdn}/artists/{$this->album->artist->artist_alias }/albums/{$this->album->album_alias}/{$catalog_num}/images/cover_front{$_size}.jpg
RELEASE_IMAGE;
        $image_check = get_headers($release_image, true);
        return (strstr($image_check[0], '200') !== false) ? $release_image : null;
    }

	private function _retrieve_last_number() {
		$result = DB::table($this->table)->where('release_catalog_num', 'LIKE', 'OBRC-%B')->orderBy('release_catalog_num', 'desc')->first();
		return $result;
	}

    public function getReleaseArtistAttribute() {
        $release_artist = null;

        if (empty($this->attributes['release_artist'])) {
            $release_artist = (!empty($this->attributes['release_artist_display_name'])) ?
                $this->attributes['release_artist_display_name'] : '';
        } else {
            $release_artist = $this->attributes['release_artist'];
        }

        return $release_artist;
    }
}

app/Http/Controllers/Api/ReleaseController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Ecommerce;
use App\Models\Release;
use App\Models\ReleaseFormat;
use App\Models\Track;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Response;

class ReleaseController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $parameters = \Illuminate\Support\Facades\Request::collect()->filter(function ($value, $key) {
            return (strpos($key, 'release_') === 0);
        })->toArray();

        if (!empty($album_id)) {
            $releases = Release::where($parameters)->orderBy('release_catalog_num')->get();
        } else {
            $releases = Release::orderBy('release_catalog_num')->get();
        }
        $releases->load('album.artist');

        return Response::json($releases);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $release = json_decode($id);

        $track_model = new Track();
        $release->ecommerce = Ecommerce::where('ecommerce_release_id', $release->release_id)->get();
        $release->tracks = $track_model->findReleaseTracks($release->release_id);
        $release->format = ReleaseFormat::where('format_id', $release->release_format_id)->first();

        return Response::json($release);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

app/Http/Controllers/ReleaseController.php
<?php

namespace App\Http\Controllers;

use App\Models\Album;
use App\Models\Release;
use App\Models\ReleaseFormat;
use App\Models\Track;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Request;
use Illuminate\Support\Facades\View;

class ReleaseController extends Controller {

	private $layout_variables = array();

	public function __construct() {

	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Contracts\View\View
	 */
	public function index()
	{
		$album_id = Request::get('album');
		if (!empty($album_id)) {
			$releases = Release::where('release_album_id', $album_id)->orderBy('release_catalog_num')->get();
		} else {
			$releases = Release::orderBy('release_catalog_num')->get();
		}
		$releases->load('album');

		$method_variables = array(
			'releases' => $releases,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('release.index', $data);
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Contracts\View\View
	 */
	public function create()
	{

		$release = new Release;
		$release->release_release_date = date('Y-m-d');

		$album_id = Request::get('album');

		if (!empty($album_id)) {
			$release->release_album_id = $album_id;
			$release->album = Album::find($album_id);
			$albums = Album::where('album_artist_id', $release->album->album_artist_id)->orderBy('album_title')->pluck('album_title', 'album_id');
		} else {
			$albums = Album::orderBy('album_title')->pluck('album_title', 'album_id');
		}

		$formats = ReleaseFormat::all()->pluck('format_alias', 'format_id');

		$method_variables = array(
			'release' => $release,
			'albums' => $albums,
			'formats' => $formats,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('release.create', $data);
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return RedirectResponse
	 */
	public function store()
	{
		$release = new Release;

		$fields = $release->getFillable();

		foreach ($fields as $field) {
			$release->{$field} = Request::get($field);
		}

		$result = $release->save();

		if ($result !== false) {
			return Redirect::route('release.show', $release->release_id)->with('message', 'Your changes were saved.');
		} else {
			return Redirect::route('album.show', $release->release_album_id )->with('error', 'Your changes were not saved.');
		}
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  Release  $id
	 * @return \Illuminate\Contracts\View\View
	 */
	public function show($id)
	{
		$track_model = new Track();
		$id->release_track_list = $track_model->findReleaseTracks($id->release_id);
		$ecommerce = $id->ecommerce->sortBy('ecommerce_list_order');

		$method_variables = array(
			'release' => $id,
			'ecommerce' => $ecommerce,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('release.show', $data);
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  Release  $id
	 * @return \Illuminate\Contracts\View\View
	 */
	public function edit($id)
	{
		$albums = Album::where('album_artist_id', $id->album->album_artist_id)->orderBy('album_title')->pluck('album_title', 'album_id');
		$formats = ReleaseFormat::pluck('format_alias', 'format_id');

		$method_variables = array(
			'release' => $id,
			'albums' => $albums,
			'formats' => $formats,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('release.edit', $data);
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  Release  $id
	 * @return RedirectResponse
	 */
	public function update($id)
	{
		$fields = $id->getFillable();

		foreach ($fields as $field) {
			$id->{$field} = Request::get($field);
		}

		$result = $id->save();

		if ($result !== false) {
			return Redirect::route('release.show', $id->release_id)->with('message', 'Your changes were saved.');
		} else {
			return Redirect::route('album.show', $id->release_album_id)->with('error', 'Your changes were not saved.');
		}
	}


	public function delete($id) {

		$method_variables = array(
			'release' => $id,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('release.delete', $data);
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  Release  $id
	 * @return RedirectResponse
	 */
	public function destroy($id)
	{
		$confirm = (boolean) Request::get('confirm');
		$release_catalog_num = $id->release_catalog_num;
		$album_id = $id->release_album_id;

		if ($confirm === true) {
			/*
			 * Tracks are currently not supported, but this bit of logic will be available if/when they are.
			$ecommerce_tracks = Track::with('ecommerce')->where('track_release_id', $id->release_id)->get();
			foreach ($ecommerce_tracks as $ecommerce_track) {
				$ecommerce_track->ecommerce()->delete();
			}
			 */

			// Remove ecommerce.
			$id->ecommerce()->delete();

			// Remove tracks.
			$id->tracks()->delete();

			// Remove releases.
			$id->delete();
			return Redirect::route('album.show', $album_id  )->with('message', 'The record was deleted.');
		} else {
			return Redirect::route('release.show', $id->release_id)->with('error', 'The record was not deleted.');
		}
	}

	public function export_id3($id) {

		$file_lines = array();
		foreach ($id->tracks as $track) {
            $isrc = (!empty($track->recording->recording_isrc_num)) ? $track->recording->recording_isrc_num : '';
			$tag = array(
				$track->release->album->artist->artist_display_name,
				$track->release->album->artist->artist_display_name,
				$track->release->album->album_title,
				date('Y', strtotime($track->release->release_release_date)),
				'Other',
				'℗ ' . date('Y', strtotime($track->release->release_release_date)) . ' Observant Records',
                $isrc,
				sprintf('%02d', $track->track_track_num),
				$track->track_title,
			);
			$tag_line = implode('|', $tag);
			$file_lines[] = $tag_line;
		}
		$file = implode("\r\n", $file_lines);

		$file_with_bom = chr(239) . chr(187) . chr(191) . $file;

		$file_name = $id->album->artist->artist_display_name . ' - ' . $id->album->album_title . '.m3u.txt';
		header('Cache-Control: private');
		header('Content-Disposition: attachment; filename="' . $file_name . '"');
		header("Content-Type: text/plain; charset=utf-8");
		echo $file_with_bom;
		die();
	}

	public function generate_catalog_num() {
		$release = new Release;
		$recording_isrc_code = (object) array('catalog_num' => $release->generate_catalog_num());
		echo json_encode($recording_isrc_code);
	}
}

resources/views/release/create.blade.php
@extends('release._form')

@section('page_title')
@if (!empty($release->album))
 &raquo; {{ $release->album->artist->artist_display_name }}
 &raquo; {{ $release->album->album_title }}
@endif
 &raquo; Add a release
@stop

@section('section_header')
<hgroup>
	<h2>
		@if (!empty($release->album))
		{{ $release->album->artist->artist_display_name }}
		<small>{{ $release->album->album_title }}</small>
		@else
		Observant Records
		@endif
	</h2>
</hgroup>
@stop

@section('section_label')
<h3>Add a release</h3>
@stop

@section('content')
{!! Form::model( $release, array( 'route' => 'release.store', 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'post' ) ) !!}
@parent
{!! Form::close() !!}
@stop


@section('sidebar')
@if (!empty($release->release_album_id))
<ul>
	<li><a href="{{ route('album.show', $release->release_album_id ) }}/">Back to <em>{{ $release->album->album_title }}</em></a></li>
</ul>
@endif
@stop

resources/views/release/edit.blade.php
@extends('release._form')

@section('page_title')
 &raquo; {{ $release->album->artist->artist_display_name }}
 &raquo; {{ $release->album->album_title }}
 &raquo; {{ $release->release_catalog_num }}
 &raquo; Edit
@stop

@section('section_header')
<hgroup>
	<h2>
		{{ $release->album->artist->artist_display_name }}
		<small>{{ $release->album->album_title }}</small>
	</h2>
</hgroup>
@stop

@section('section_label')
<h3>
	Edit release
	@if (!empty($release->release_catalog_num))
	<small>{{ $release->release_catalog_num }}</small>
	@endif
</h3>
@stop

@section('content')
{!! Form::model( $release, array( 'route' => array('release.update', $release->release_id), 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'put' ) ) !!}
@parent
{!! Form::close() !!}
@stop

@section('sidebar')
<p>
	<img src="{{ OBSERVANTRECORDS_CDN_BASE_URI }}/artists/{{ $release->album->artist->artist_alias }}/albums/{{ $release->album->album_alias }}/{{ strtolower($release->release_catalog_num) }}/images/cover_front_medium.jpg" width="230" />
</p>

<ul>
	<li><a href="{{ route('release.show', $release->release_id ) }}/">Back to <em>{{ $release->album->album_title }}</em> @if (!empty($release->release_catalog_num)) ({{ $release->release_catalog_num }}) @else (TBD) @endif </a></li>
</ul>

@stop

resources/views/release/show.blade.php
@extends('layout')

@section('page_title')
 &raquo; {{ $release->album->artist->artist_display_name }}
 &raquo; {{ $release->album->album_title }}
@if (!empty($release->release_catalog_num))
 &raquo; {{ $release->release_catalog_num }}
@endif
@stop

@section('section_header')
<hgroup>
	<h2>
		{{ $release->album->artist->artist_display_name }}
		<small>{{ $release->album->album_title }}</small>
	</h2>
</hgroup>
@stop

@section('section_label')
<h3>
	Release info
	@if (!empty($release->release_catalog_num))
	<small>{{ $release->release_catalog_num }}</small>
	@endif
</h3>
@stop

@section('content')

<ul class="list-inline">
	<li><a href="{{ route( 'release.edit', $release->release_id ) }}" class="btn btn-primary">Edit</a></li>
	<li><a href="{{ route( 'release.delete', $release->release_id ) }}" class="btn btn-warning">Delete</a></li>
</ul>

<ul class="two-column-bubble-list">
	<li>
		<div>
			<label>Format</label> {{ $release->format->format_name }}
		</div>
	</li>
	@if (!empty($release->release_label))
	<li>
		<div>
			<label>Label</label> {{ $release->release_label }}
		</div>
	</li>
	@endif
	@if (!empty($release->release_alternate_title))
	<li>
		<div>
			<label>Alternate title</label> {{ $release->release_alternate_title }}
		</div>
	</li>
	@endif
	@if (!empty($release->release_upc_num))
	<li>
		<div>
			<label>UPC No.</label> {{ $release->release_upc_num }}
		</div>
	</li>
	@endif
	@if (!empty($release->release_catalog_num))
	<li>
		<div>
			<label>Catalog No.</label> {{ $release->release_catalog_num }}
		</div>
	</li>
	@endif
	@if (!empty($release->release_release_date))
	<li>
		<div>
			<label>Release Date</label> {{ date('Y-m-d', strtotime($release->release_release_date)) }}
		</div>
	</li>
	@endif
	@if (!empty($release->release_alias))
	<li>
		<div>
			<label>Alias</label> {{ $release->release_alias }}
		</div>
	</li>
	@endif
	@if (!empty($release->release_image))
	<li>
		<div>
			<label>Image</label> {{ $release->release_image }}
		</div>
	</li>
	@endif
	<li>
		<div>
			<label>Visible?</label> <input type="checkbox" disabled="disabled" value="1" @if (($release->release_is_visible==true)) checked @endif />
		</div>
	</li>
</ul>

<h3>Tracks</h3>

{!! Form::open( array( 'route' => array( 'track.save-order' ), 'id' => 'save-order-form' ) ) !!}
<ul class="list-inline">
	<li><a href="{{ route( 'track.create', array('release' => $release->release_id) ) }}" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Add a track</a></li>
	@if (count($release->release_track_list) > 0)
	<li><a href="{{ route( 'release.export-id3' , $release->release_id ) }}" class="btn btn-default">Export ID3 data</a></li>
	<li>
		{!! Form::button( 'Save track order', array('id' => 'save-order', 'class' => 'btn btn-default') ) !!}
		{!! Form::hidden( 'track_id' ) !!}
	</li>
	@endif
</ul>
<p>

</p>
{!! Form::close() !!}

@if (count($release->release_track_list) > 0)
<ol class="disc-list">
	@foreach ($release->release_track_list as $disc_num => $tracks)
	<li> <h4>Disc: <span class="disc-num-display">{{ $disc_num }}</span>:</h4>
		<ol class="track-list">
			@foreach ($tracks as $track)
			<li>
				<div>
					<ul class="list-inline">
						<li><a href="{{ route( 'track.edit', $track->track_id ) }}" title="[Edit]"><span class="glyphicon glyphicon-pencil"></span></a></li>
						<li><a href="{{ route( 'track.delete', $track->track_id ) }}" title="[Delete]"><span class="glyphicon glyphicon-remove"></span></a></li>
						<li>
							<span class="track-num-display">{{ $track->track_track_num }}</span>.
							<a href="{{ route( 'track.show',$track->track_id ) }}">
								@if ( $track->track_artist_id )
									{{ $track->artist->artist_display_name }} &ndash;
								@endif
								{{ $track->track_title }}
							</a>
							<input type="hidden" name="track_id" value="{{ $track->track_id }}" />
							<input type="hidden" name="track_disc_num" value="{{ $track->track_disc_num }}" />
						</li>
					</ul>
				</div>
			</li>
			@endforeach
		</ol>
	</li>
	@endforeach
</ol>

<div id="save-order-dialog">
	<p class="msg"></p>
</div>

<script type="text/javascript">
	$('.track-list').sortable({
		update: function (event, ui) {
			var new_track_num = 1;
			$(this).children().each(function () {
				$(this).find('.track-num-display').html(new_track_num);
				new_track_num++;
			});
		}
	});
	if ($('.disc-list').children().length > 1) {
		$('.disc-list').sortable({
			update: function (event, ui) {
				var new_disc_num = 1;
				$(this).children().each(function () {
					$(this).find('.disc-num-display').html(new_disc_num);
					$(this).find('.track-list li').each(function () {
						$(this).find('input[name=track_disc_num]').val(new_disc_num);
					});
					new_disc_num++;
				});
			}
		});
	}
	$('#save-order-dialog').dialog({
		autoOpen: false,
		modal: true,
		buttons: {
			"OK": function () {
				$(this).dialog('close');
			}
		}
	});
	$('#save-order').click(function () {
		var tracks = [], track_disc, track_num, track_id, track_info;
		$('.track-list').children().each(function () {
			track_num = $(this).find('.track-num-display').html();
			track_id = $(this).find('input[name=track_id]').val();
			track_disc = $(this).find('input[name=track_disc_num]').val();
			track_info = {
				'track_id': track_id,
				'track_track_num': track_num,
				'track_disc_num': track_disc
			}
			tracks.push(track_info);
		});
		var _token = $('#save-order-form').find('input[name=_token]').val();
		var url = $('#save-order-form').attr('action');
		var data = {
			'tracks': tracks,
			'_token': _token
		};
		$.post(url, data, function (result) {
			$('#save-order-dialog').dialog('open');
			$('#save-order-dialog').find('.msg').html(result);
		}).error(function (result) {
			var error_msg = 'Your request could not be completed. The following error was given: ' + result.statusText;
			$('#save-order-dialog').dialog('open');
			$('#save-order-dialog').find('.msg').html(error_msg);
		});
	});
</script>

@else
<p>
	This release has no tracks.
</p>
@endif


<h4>Ecommerce links</h4>

{!! Form::open( array( 'route' => array( 'ecommerce.save-order' ), 'id' => 'save-ecommerce-form' ) ) !!}
<ul class="list-inline">
	<li><a href="{{ route( 'ecommerce.create', array('release' => $release->release_id) ) }}" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Add an ecommerce link</a></li>
	@if (count($release->ecommerce) > 0)
	<li>{!! Form::button( 'Save ecommerce link order', array('id' => 'save-ecommerce-order', 'class' => 'btn btn-default') ) !!}</li>
	@endif
</ul>
{!! Form::close() !!}

@if (count($ecommerce) > 0)
<ul class="ecommerce-list">
	@foreach ($ecommerce->values() as $ecommerce)
	<li>
		<div>
			<ul class="list-inline">
				<li><a href="{{ route( 'ecommerce.edit', $ecommerce->ecommerce_id ) }}"><span class="glyphicon glyphicon-pencil"></span></a></li>
				<li><a href="{{ route( 'ecommerce.delete', $ecommerce->ecommerce_id ) }}"><span class="glyphicon glyphicon-remove"></span></a></li>
				<li>
					<span class="ecommerce-list-order">{{ $ecommerce->ecommerce_list_order }}</span>. <a href="{{ route( 'ecommerce.show', $ecommerce->ecommerce_id) }}">{{ $ecommerce->ecommerce_label }}</a>
					<input type="hidden" name="ecommerce_id" value="{{ $ecommerce->ecommerce_id }}" />
				</li>
			</ul>
		</div>
	</li>
	@endforeach
</ul>

<div id="save-list-order-dialog">
	<p class="msg"></p>
</div>

<script type="text/javascript">
	$('.ecommerce-list').sortable({
		update: function (event, ui) {
			var new_list_order = 1;
			$(this).children().each(function () {
				$(this).find('.ecommerce-list-order').html(new_list_order);
				new_list_order++;
			});
		}
	});
	$('#save-list-order-dialog').dialog({
		autoOpen: false,
		modal: true,
		buttons: {
			"OK": function () {
				$(this).dialog('close');
			}
		}
	});
	$('#save-ecommerce-order').click(function () {
		var ecomm_links = [], ecomm_list_order, ecomm_id, ecomm_info;
		$('.ecommerce-list').children().each(function () {
			ecomm_list_order = $(this).find('.ecommerce-list-order').html();
			ecomm_id = $(this).find('input[name=ecommerce_id]').val();
			ecomm_info = {
				'ecommerce_id': ecomm_id,
				'ecommerce_list_order': ecomm_list_order,
			}
			ecomm_links.push(ecomm_info);
		});
		var _token =  $('#save-ecommerce-form').find('input[name=_token]').val();
		var url = $('#save-ecommerce-form').attr('action');
		var data = {
			'ecommerce': ecomm_links,
			'_token': _token
		};
		$.post(url, data, function (result) {
			$('#save-list-order-dialog').dialog('open');
			$('#save-list-order-dialog').find('.msg').html(result);
		}).error(function (result) {
			var error_msg = 'Your request could not be completed. The following error was given: ' + result.statusText;
			$('#save-list-order-dialog').dialog('open');
			$('#save-list-order-dialog').find('.msg').html(error_msg);
		});
	});
</script>
@else
<p>This release has no ecommerce links.</p>
@endif

@stop

@section('sidebar')
	@if (!empty($release->get_cdn_image() ))
	<p>
		<img src="{{ $release->get_cdn_image('medium') }}" width="230" />
	</p>
	@endif

<ul class="list-unstyled">
	<li>&laquo; <a href="{{ route('album.show', $release->release_album_id ) }}/">Back to <em>{{ $release->album->album_title }}</em></a></li>
</ul>

@stop