routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::group(['middleware' => 'auth'], function () {
	Route::get('/', array( 'as' => 'index', 'uses' => 'ArtistController@index' ) );
	Route::get('/home', array( 'as' => 'home', 'uses' => 'ArtistController@index' ) );

// Artist
	Route::model('artist', 'App\Models\Artist');
	Route::resource('artist', 'ArtistController');
	Route::get( '/artist/{artist}/delete', array( 'as' => 'artist.delete', 'uses' => 'ArtistController@delete' ) );

// Album
	Route::model('album', 'App\Models\Album');
	Route::resource('album', 'AlbumController');
	Route::get( '/album/{album}/delete', array( 'as' => 'album.delete', 'uses' => 'AlbumController@delete' ) );
	Route::post( '/album/save-order', array( 'as' => 'album.save-order', 'uses' => 'AlbumController@save_order' ) );

// Release
	Route::model('release', 'App\Models\Release');
	Route::resource('release', 'ReleaseController');
	Route::get( '/release/{release}/delete', array( 'as' => 'release.delete', 'uses' => 'ReleaseController@delete' ) );
	Route::get( '/release/{release}/export-id3', array( 'as' => 'release.export-id3', 'uses' => 'ReleaseController@export_id3' ) );
	Route::post( '/release/generate-catalog-num', array( 'as' => 'release.catalog-num', 'uses' => 'ReleaseController@generate_catalog_num' ) );

// Tracks
	Route::model('track', 'App\Models\Track');
	Route::get( '/track/{track}/delete', array( 'as' => 'track.delete', 'uses' => 'TrackController@delete' ) );
	Route::post( '/track/save-order', array( 'as' => 'track.save-order', 'uses' => 'TrackController@save_order' ) );
	Route::resource('track', 'TrackController');

// Audio
	Route::model('audio', 'App\Models\Audio');
	Route::get( '/audio/{audio}/delete/', array( 'as' => 'audio.delete', 'uses' => 'AudioController@delete' ) );
	Route::resource('audio', 'AudioController');

// Ecommerce
	Route::model('ecommerce', 'App\Models\Ecommerce');
	Route::get( '/ecommerce/{ecommerce}/delete', array( 'as' => 'ecommerce.delete', 'uses' => 'EcommerceController@delete' ) );
	Route::post( '/ecommerce/save-order', array( 'as' => 'ecommerce.save-order', 'uses' => 'EcommerceController@save_order' ) );
	Route::resource('ecommerce', 'EcommerceController');

// Songs
	Route::model('song', 'App\Models\Song');
	Route::get( '/song/{song}/delete', array( 'as' => 'song.delete', 'uses' => 'SongController@delete' ) );
	Route::get( '/song/{song}/lyrics', array( 'as' => 'song.lyrics', 'uses' => 'SongController@lyrics' ) );
	Route::resource('song', 'SongController');

// Recordings
	Route::model('recording', 'App\Models\Recording');
	Route::get( '/recording/{recording}/delete', array( 'as' => 'recording.delete', 'uses' => 'RecordingController@delete' ) );
	Route::post( '/recording/generate-isrc', array( 'as' => 'recording.isrc', 'uses' => 'RecordingController@generate_isrc' ) );
	Route::resource('recording', 'RecordingController');

// Profile
	Route::model('user', 'App\Models\User');
	Route::resource('user', 'UserController');
	Route::get( '/user/{user}/delete', array( 'as' => 'user.delete', 'uses' => 'UserController@delete' ) );
});

Auth::routes();

app/Models/Album.php
<?php
/**
 * Created by PhpStorm.
 * User: gregbueno
 * Date: 5/26/14
 * Time: 5:26 PM
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Album extends Model {

	protected $table = 'ep4_albums';
	protected $primaryKey = 'album_id';
	protected $softDelete = true;
	protected $fillable = array(
		'album_artist_id',
        'album_artist_display_name',
		'album_primary_release_id',
		'album_format_id',
		'album_ctype_locale',
		'album_title',
		'album_order',
		'album_alias',
		'album_image',
		'album_music_description',
		'album_release_date',
		'album_is_visible',
	);
	protected $guarded = array(
		'artist_id',
	);

	public function artist() {
		return $this->belongsTo('App\Models\Artist', 'album_artist_id', 'artist_id');
	}

	public function releases() {
		return $this->hasMany('App\Models\Release', 'release_album_id', 'album_id');
	}

	public function primary_release() {
		return $this->hasOne('App\Models\Release', 'release_id', 'album_primary_release_id');
	}

	public function format() {
		return $this->hasOne('App\Models\AlbumFormat', 'format_id', 'album_format_id');
	}

	public function scopeEponymous4($query) {
		return $query->where('album_artist_id', '=', 1);
	}

	public function scopeEmptyEnsemble($query) {
		return $query->where('album_artist_id', '=', 2);
	}

    public function getAlbumArtistAttribute() {
        $album_artist = null;

        if (empty($this->attributes['album_artist'])) {
            $album_artist = (!empty($this->attributes['album_artist_display_name'])) ?
                $this->attributes['album_artist_display_name'] : '';
        } else {
            $album_artist = $this->attributes['album_artist'];
        }

        return $album_artist;
    }
}

app/Http/Controllers/AlbumController.php
<?php

namespace App\Http\Controllers;

use App\Models\Artist;
use App\Models\Album;
use App\Models\AlbumFormat;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Request;
use Illuminate\Support\Facades\View;

class AlbumController extends Controller {

	private $layout_variables = array();

	public function __construct() {
		$format_list = array();
		$formats = AlbumFormat::orderBy('format_alias')->get();
		foreach ($formats as $format) {
			$format_list[$format->format_id] = $format->format_alias;
		}

		$this->layout_variables = array(
			'formats' => $format_list,
			'locales' => array('en', 'jp'),
		);
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Contracts\View\View
	 */
	public function index()
	{
		$artist_id = Request::get('artist');
		if (!empty($artist_id)) {
			$albums = Album::where('album_artist_id', $artist_id)->orderBy('album_title')->get();
		} else {
			$albums = Album::orderBy('album_title')->get();
		}
		$albums->load('artist');

		$method_variables = array(
			'albums' => $albums,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('album.index', $data);
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Contracts\View\View
	 */
	public function create()
	{
		$artist_id = Request::get('artist');

		$album = new Album;
		$album->album_release_date = date('Y-m-d');
		$album->album_ctype_locale = 'en';
		if (!empty($artist_id)) {
			$album->album_artist_id = $artist_id;
			$album->artist = Artist::find($artist_id);
		}

		$artists = Artist::orderBy('artist_last_name')->pluck('artist_display_name', 'artist_id');

		$method_variables = array(
			'album' => $album,
			'artists' => $artists,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('album.create', $data);
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return RedirectResponse
	 */
	public function store()
	{
		$id = new Album;

		$fields = $id->getFillable();

		foreach ($fields as $field) {
			$id->{$field} = Request::get($field);
		}

		$result = $id->save();

		if ($result !== false) {
			return Redirect::route('album.show', $id->album_id)->with('message', 'Your changes were saved.');
		} else {
			return Redirect::route('artist.show', $id->album_artist_id)->with('error', 'Your changes were not saved.');
		}
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  Album  $id
	 * @return \Illuminate\Contracts\View\View
	 */
	public function show($id)
	{
		$method_variables = array(
			'album' => $id,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('album.show', $data);
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
     * @return \Illuminate\Contracts\View\View
	 */
	public function edit($id)
	{
		$releases = $id->releases->pluck('release_catalog_num', 'release_id');
		$artists = Artist::orderBy('artist_last_name')->pluck('artist_display_name', 'artist_id');

		$method_variables = array(
			'album' => $id,
			'releases' => $releases,
			'artists' => $artists,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('album.edit', $data);
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return RedirectResponse
	 */
	public function update($id)
	{
		$fields = $id->getFillable();

		foreach ($fields as $field) {
			$id->{$field} = Request::get($field);
		}

		$result = $id->save();

		if ($result !== false) {
			return Redirect::route('album.show', $id->album_id)->with('message', 'Your changes were saved.');
		} else {
			return Redirect::route('artist.show', $id->album_artist_id)->with('error', 'Your changes were not saved.');
		}
	}


	public function delete($id) {

		$method_variables = array(
			'album' => $id,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('album.delete', $data);
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return RedirectResponse
	 */
	public function destroy($id)
	{
		$confirm = (boolean) Request::get('confirm');
		$album_title = $id->album_title;
		$artist_id = $id->album_artist_id;

		if ($confirm === true) {
			if (count($id->releases) > 0) {
				foreach ($id->releases as $release) {
					/*
					 * This bit of logic is not yet supported.
					foreach ($release->tracks as $track) {
						$track->ecommerce()->delete();
					}
					 */

					// Remove ecommerce.
					$release->ecommerce()->delete();

					// Remove tracks.
					$release->tracks()->delete();
				}

				// Remove releases.
				$id->releases()->delete();
			}

			// Remove album.
			$id->delete();
			return Redirect::route('artist.show', $artist_id )->with('message', $album_title . ' was deleted.');
		} else {
			return Redirect::route('album.show', $id->album_id)->with('error', $album_title . ' was not deleted.');
		}
	}

	public function save_order() {
		$albums = Request::get('albums');

		$is_success = true;
		if (count($albums) > 0) {
			foreach ($albums as $album) {
				if (false === $this->_update_album($album['album_id'], $album)) {
					$is_success = false;
					$error = 'Album order was not saved.';
					break;
				}
			}
		}

		echo ($is_success == true) ? 'Album order has been saved.' : $error;
	}

	private function _update_album($album_id, $input) {
		$album = Album::find($album_id);

		$album->album_order = $input['album_order'];

		return $album->save();
	}


}

app/Http/Controllers/Api/AlbumController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Album;
use App\Models\AlbumFormat;
use App\Models\Release;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Response;

class AlbumController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {

        $parameters = \Illuminate\Support\Facades\Request::collect()->filter(function ($value, $key) {
            return (strpos($key, 'album_') === 0);
        })->toArray();

        if (!empty($parameters)) {
            $albums = Album::where($parameters)->orderBy('album_title')->get();
        } else {
            $albums = Album::orderBy('album_title')->get();
        }
        $albums->load('artist');

        return Response::json($albums);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $album = json_decode($id);

        $album->primary_release = Release::with(['ecommerce', 'tracks.song', 'format'])->where('release_id', $album->album_primary_release_id)->first();
        $album->format = AlbumFormat::where('format_id', $album->album_format_id)->first();

        return Response::json($album);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

resources/views/album/_form.blade.php
@extends('layout')

@section('content')

@if (!empty($artists))
<div class="form-group">
	{!! Form::label( 'album_artist_id', 'Artist:', array( 'class' => 'col-sm-2 control-label' ) ) !!}
	<div class="col-sm-10">
		{!! Form::select( 'album_artist_id', $artists, $album->album_artist_id, array( 'class' => 'form-control' ) ) !!}
	</div>
</div>
@else
{!! Form::hidden( 'album_artist_id' , $album->album_artist_id) !!}
@endif

<div class="form-group">
	{!! Form::label( 'album_artist_display_name', 'Artist display name:', array( 'class' => 'col-sm-2 control-label' ) ) !!}
	<div class="col-sm-10">
		{!! Form::text( 'album_artist_display_name', $album->album_artist_display_name, array( 'class' => 'form-control' ) ) !!}
	</div>
</div>

<div class="form-group">
	{!! Form::label( 'album_title', 'Title:', array( 'class' => 'col-sm-2 control-label' ) ) !!}
	<div class="col-sm-10">
		{!! Form::text( 'album_title', $album->album_title, array( 'class' => 'form-control' ) ) !!}
	</div>
</div>

<div class="form-group">
	{!! Form::label( 'album_alias', 'Alias:', array( 'class' => 'col-sm-2 control-label' ) ) !!}
	<div class="col-sm-10">
		{!! Form::text( 'album_alias', $album->album_alias, array( 'class' => 'form-control' ) ) !!}
	</div>
</div>

<div class="form-group">
	{!! Form::label( 'album_release_date', 'Release date:', array( 'class' => 'col-sm-2 control-label' ) ) !!}
	<div class="col-sm-10">
		{!! Form::text( 'album_release_date', date('Y-m-d', strtotime($album->album_release_date)), array( 'class' => 'form-control' ) ) !!}
	</div>
</div>

@if (!empty($album->album_id))
<div class="form-group">
	{!! Form::label( 'album_primary_release_id', 'Primary release:', array( 'class' => 'col-sm-2 control-label' ) ) !!}
	<div class="col-sm-10">
		{!! Form::select( 'album_primary_release_id', $releases, $album->album_primary_release_id, array( 'class' => 'form-control' ) ) !!}
	</div>
</div>
@endif

<div class="form-group">
	{!! Form::label( 'album_ctype_locale', 'Title locale:', array( 'class' => 'col-sm-2 control-label' ) ) !!}
	<div class="col-sm-10">
		{!! Form::select( 'album_ctype_locale', $locales, $album->album_ctype_locale, array( 'class' => 'form-control' ) ) !!}
	</div>
</div>

<div class="form-group">
	{!! Form::label( 'album_format_id', 'Format:', array( 'class' => 'col-sm-2 control-label' ) ) !!}
	<div class="col-sm-10">
		{!! Form::select( 'album_format_id', $formats, $album->album_format_id, array( 'class' => 'form-control' ) ) !!}
	</div>
</div>

<div class="form-group">
	{!! Form::label( 'album_music_description', 'Description:', array( 'class' => 'col-sm-2 control-label' ) ) !!}
	<div class="col-sm-10">
		{!! Form::textarea( 'album_music_description', $album->album_music_description, array( 'class' => 'form-control' ) ) !!}
	</div>
</div>

<div class="form-group">
	{!! Form::label( 'album_order', 'Order:', array( 'class' => 'col-sm-2 control-label' ) ) !!}
	<div class="col-sm-10">
		{!! Form::text( 'album_order', $album->album_order, array( 'class' => 'form-control' ) ) !!}
	</div>
</div>


<div class="form-group">
	{!! Form::label( 'album_is_visible', 'Visibility:', array( 'class' => 'col-sm-2 control-label' ) ) !!}
	<div class="col-sm-10">
		<div class="radio">
			<label>
				{!! Form::radio( 'album_is_visible', 1, ($album->album_is_visible == 1) ) !!} Show
			</label>
		</div>
		<div class="radio">
			<label>
				{!! Form::radio( 'album_is_visible', 0, ($album->album_is_visible == 0) ) !!} Hide
			</label>
		</div>
	</div>
</div>

<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
        <ul class="list-inline">
            <li>{!! Form::submit( 'Save', array( 'class' => 'btn btn-primary' ) ) !!}</li>
            <li>
                @if (!empty( $album->album_id))
                    <a href="{{ route( 'album.show', $album->album_id ) }}" class="btn btn-default">Cancel</a>
                @elseif (!empty($album->album_artist_id))
                    <a href="{{ route( 'artist.show', $album->album_artist_id ) }}" class="btn btn-default">Cancel</a>
                @else
                    <a href="{{ route( 'album.index' ) }}" class="btn btn-default">Cancel</a>
                @endif
            </li>
        </ul>
	</div>
</div>

<script type="text/javascript">
	(function ($) {
		$('#album_primary_release_id').chosen();
		$('#album_format_id').chosen();
		$('#album_artist_id').chosen();
        $('#album_ctype_locale').chosen();

		// Date pickers.
		$('#album_release_date').datepicker({
			dateFormat: 'yy-mm-dd'
		});

		$('#album_title').keyup(function () {
			var alias = this.value.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9\-]+/g, '').replace(/(^-|-$)/, '');
			$('#album_alias').val(alias);
		});
	})(jQuery);
</script>

@stop

resources/views/album/create.blade.php
@extends('album._form')

@section('page_title')
@if (!empty($album->artist->artist_display_name))
 &raquo; {{ $album->artist->artist_display_name }}
@endif
 &raquo; Album
 &raquo; Add
@stop

@section('section_header')
<h2>
	@if (!empty($album->artist->artist_display_name))
	{{ $album->artist->artist_display_name }}
	@else
	Observant Records
	@endif
</h2>
@stop

@section('section_label')
<h3>Add a new album</h3>
@stop

@section('content')
{!! Form::model( $album, array( 'route' => 'album.store', 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'post' ) ) !!}
@parent
{!! Form::close() !!}
@stop

resources/views/album/delete.blade.php
@extends('layout')

@section('page_title')
 &raquo; {{ $album->artist->artist_display_name }}
 &raquo; {{ $album->album_title }}
 &raquo; Delete
@stop

@section('section_header')
<hgroup>
	<h2>
		{{ $album->artist->artist_display_name }}
		<small>{{ $album->album_title }}</small>
	</h2>
</hgroup>
@stop

@section('section_label')
<h3>Delete album</h3>
@stop

@section('content')

<p>
	You are about to delete <strong><em>{{ $album->album_title }}</em></strong> from the database. Deleting an album also removes all releases and tracks related to this album.
</p>

<p>
	Are you sure you want to do this?
</p>

{!! Form::model( $album, array( 'route' => array( 'album.destroy', $album->album_id), 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'delete' ) ) !!}

<div class="form-group">
	<div class="col-sm-12">
		<div class="radio">
			<label>
				{!! Form::radio('confirm', '1') !!} Yes, I want to delete {{ $album->album_title }}.
			</label>
		</div>
		<div class="radio">
			<label>
				{!! Form::radio('confirm', '0') !!} No, I don't want to delete {{ $album->album_title }}.
			</label>
		</div>
	</div>
</div>

<div class="form-group">
	<div class="col-sm-12">
		{!! Form::submit('Confirm', array( 'class' => 'btn btn-danger' )) !!}
	</div>
</div>


{!! Form::close() !!}

@stop

resources/views/album/edit.blade.php
@extends('album._form')

@section('page_title')
 &raquo; {{ $album->artist->artist_display_name }}
 &raquo; {{ $album->album_title }}
 &raquo; Edit
@stop

@section('section_header')
<hgroup>
	<h2>
		{{ $album->artist->artist_display_name }}
		<small>{{ $album->album_title }}</small>
	</h2>
</hgroup>
@stop

@section('section_label')
<h3>Edit album info</h3>
@stop

@section('content')
{!! Form::model( $album, array( 'route' => array('album.update', $album->album_id), 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'put' ) ) !!}
@parent
{!! Form::close() !!}
@stop

resources/views/album/index.blade.php
@extends('layout')

@section('page_title')
 &raquo; Albums &raquo; Browse
@stop

@section('section_header')
<h2>Observant Records</h2>
@stop

@section('section_label')
<h3>
	Albums
	<small>Browse</small>
</h3>
@stop

@section('content')

<p>
	<a href="{{ route('album.create') }}" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Add an album</a>
</p>

@if (count($albums) > 0)
<ol class="track-list">
	@foreach ($albums as $album)
	<li>
		<div>
			<a href="{{ route( 'album.edit', $album->album_id ) }}"><span class="glyphicon glyphicon-pencil"></span></a>
			<a href="{{ route( 'album.delete', $album->album_id ) }}"><span class="glyphicon glyphicon-remove"></span></a>
			<a href="{{ route( 'album.show', $album->album_id ) }}">{{ $album->album_title }} ({{ $album->artist->artist_display_name}})</a>
		</div>
	</li>
	@endforeach
</ol>
@endif

@stop

resources/views/album/show.blade.php
@extends('layout')

@section('page_title')
 &raquo; {{ $album->artist->artist_display_name }}
 &raquo; {{ $album->album_title }}
@stop

@section('section_header')
<hgroup>
	<h2>
		{{ $album->artist->artist_display_name }}
		<small>{{ $album->album_title }}</small>
	</h2>
</hgroup>
@stop

@section('section_label')
<h3>Album info</h3>
@stop

@section('content')

<ul class="list-inline">
	<li><a href="{{ route('album.edit', $album->album_id) }}" class="btn btn-primary">Edit</a></li>
	<li><a href="{{ route('album.delete', $album->album_id) }}" class="btn btn-warning">Delete</a></li>
</ul>

<ul class="two-column-bubble-list">
	<li>
		<div>
			<label>Title</label> {{ $album->album_title }}
		</div>
	</li>
	@if (!empty($album->album_ctype_locale))
	<li>
		<div>
			<label>Title locale</label> {{ $album->album_ctype_locale }}
		</div>
	</li>
	@endif
	@if (!empty($album->album_release_date))
	<li>
		<div>
			<label>Release Date</label> {{ date( 'm/d/Y', strtotime( $album->album_release_date ) ) }}
		</div>
	</li>
	@endif
	@if (!empty($album->album_alias))
	<li>
		<div>
			<label>Alias</label> {{ $album->album_alias }}
		</div>
	</li>
	@endif
	@if (!empty($album->album_image))
	<li>
		<div>
			<label>Image</label> {{ $album->album_image }}
		</div>
	</li>
	@endif
	@if (!empty($primary_release))
	<li>
		<div>
			<label>Primary release</label> {{ $primary_release->release_catalog_num }}
		</div>
	</li>
	@endif
	<li>
		<div>
			<label>Visible?</label> <input type="checkbox" disabled="disabled" value="1"
			@if ($album->album_is_visible==true)
			checked="checked"
			@endif />
		</div>
	</li>
</ul>


<h3>Releases</h3>

<ul class="list-inline">
	<li><a href="{{ route('release.create', array( 'album' => $album->album_id )) }}" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Add a release</a></li>
</ul>

@if (count($album->releases) > 0)
<table class="table">
	<thead>
	<tr>
		<th>&nbsp;</th>
		<th>Cover</th>
		<th>Catalog No.</th>
		<th>UPC</th>
	</tr>
	</thead>
	<tbody>
	</tbody>
	@foreach ($album->releases as $release)
	<tr>
		<td>
			<div>
				<ul class="list-inline">
					<li><a href="{{ route( 'release.edit', $release->release_id ) }}/"><span class="glyphicon glyphicon-pencil" title="[Edit]"></span> <span class="sr-only">Edit</span></a></li>
					<li><a href="{{ route( 'release.delete', $release->release_id ) }}/"><span class="glyphicon glyphicon-remove" title="[Delete]"></span> <span class="sr-only">Delete</span></a></li>
				</ul>
			</div>
		</td>
		<td>
			<a href="{{ route( 'release.show', $release->release_id ) }}">
				@if (!empty($release->get_cdn_image() ))
				<img src="{{ $release->get_cdn_image('small') }}" width="50" height="50" />
				@else
				No cover uploaded
				@endif
			</a>
		</td>
		<td>
			<a href="{{ route( 'release.show', $release->release_id ) }}">
			@if (!empty($release->release_catalog_num))
			{{ $release->release_catalog_num }}
			@else
			Unassigned
			@endif
			</a>
		</td>
		<td>
			@if (!empty($release->release_upc_num))
			{{ $release->release_upc_num }}
			@else
			Unassigned
			@endif
		</td>
	</tr>
	@endforeach
</table>
@else
<p>
	This album has no releases. Please add one.
</p>
@endif


@stop