routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::group(['middleware' => 'auth'], function () {
	Route::get('/', array( 'as' => 'index', 'uses' => 'ArtistController@index' ) );
	Route::get('/home', array( 'as' => 'home', 'uses' => 'ArtistController@index' ) );

// Artist
	Route::model('artist', 'App\Models\Artist');
	Route::resource('artist', 'ArtistController');
	Route::get( '/artist/{artist}/delete', array( 'as' => 'artist.delete', 'uses' => 'ArtistController@delete' ) );

// Album
	Route::model('album', 'App\Models\Album');
	Route::resource('album', 'AlbumController');
	Route::get( '/album/{album}/delete', array( 'as' => 'album.delete', 'uses' => 'AlbumController@delete' ) );
	Route::post( '/album/save-order', array( 'as' => 'album.save-order', 'uses' => 'AlbumController@save_order' ) );

// Release
	Route::model('release', 'App\Models\Release');
	Route::resource('release', 'ReleaseController');
	Route::get( '/release/{release}/delete', array( 'as' => 'release.delete', 'uses' => 'ReleaseController@delete' ) );
	Route::get( '/release/{release}/export-id3', array( 'as' => 'release.export-id3', 'uses' => 'ReleaseController@export_id3' ) );
	Route::post( '/release/generate-catalog-num', array( 'as' => 'release.catalog-num', 'uses' => 'ReleaseController@generate_catalog_num' ) );

// Tracks
	Route::model('track', 'App\Models\Track');
	Route::get( '/track/{track}/delete', array( 'as' => 'track.delete', 'uses' => 'TrackController@delete' ) );
	Route::post( '/track/save-order', array( 'as' => 'track.save-order', 'uses' => 'TrackController@save_order' ) );
	Route::resource('track', 'TrackController');

// Audio
	Route::model('audio', 'App\Models\Audio');
	Route::get( '/audio/{audio}/delete/', array( 'as' => 'audio.delete', 'uses' => 'AudioController@delete' ) );
	Route::resource('audio', 'AudioController');

// Ecommerce
	Route::model('ecommerce', 'App\Models\Ecommerce');
	Route::get( '/ecommerce/{ecommerce}/delete', array( 'as' => 'ecommerce.delete', 'uses' => 'EcommerceController@delete' ) );
	Route::post( '/ecommerce/save-order', array( 'as' => 'ecommerce.save-order', 'uses' => 'EcommerceController@save_order' ) );
	Route::resource('ecommerce', 'EcommerceController');

// Songs
	Route::model('song', 'App\Models\Song');
	Route::get( '/song/{song}/delete', array( 'as' => 'song.delete', 'uses' => 'SongController@delete' ) );
	Route::get( '/song/{song}/lyrics', array( 'as' => 'song.lyrics', 'uses' => 'SongController@lyrics' ) );
	Route::resource('song', 'SongController');

// Recordings
	Route::model('recording', 'App\Models\Recording');
	Route::get( '/recording/{recording}/delete', array( 'as' => 'recording.delete', 'uses' => 'RecordingController@delete' ) );
	Route::post( '/recording/generate-isrc', array( 'as' => 'recording.isrc', 'uses' => 'RecordingController@generate_isrc' ) );
	Route::resource('recording', 'RecordingController');

// Profile
	Route::model('user', 'App\Models\User');
	Route::resource('user', 'UserController');
	Route::get( '/user/{user}/delete', array( 'as' => 'user.delete', 'uses' => 'UserController@delete' ) );
});

Auth::routes();

app/Models/Song.php
<?php
/**
 * Created by PhpStorm.
 * User: gregbueno
 * Date: 5/26/14
 * Time: 5:58 PM
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Song extends Model {

	protected $table = 'ep4_songs';
	protected $primaryKey = 'song_id';
	protected $softDelete = true;
	protected $fillable = array(
		'song_primary_artist_id',
		'song_title',
		'song_alias',
		'song_author',
		'song_abstract',
		'song_lyrics',
		'song_influences',
		'song_style',
		'song_written_date',
		'song_revised_date',
		'song_recorded_date',
	);
	protected $guarded = array(
		'song_id',
		'song_deleted',
	);


	public function artist() {
		return $this->belongsTo('App\Models\Artist', 'song_primary_artist_id', 'artist_id');
	}

	public function recordings() {
		return $this->hasMany('App\Models\Recording', 'recording_song_id', 'song_id');
	}

	public function tracks() {
		return $this->hasMany('App\Models\Track', 'track_song_id', 'song_id');
	}

} 

app/Http/Controllers/SongController.php
<?php

namespace App\Http\Controllers;

use App\Models\Artist;
use App\Models\Song;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Request;
use Illuminate\Support\Facades\View;

class SongController extends Controller {

	private $layout_variables = array();

	public function __construct() {

	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$artist_id = Request::get('artist');

		if (!empty($artist_id)) {
			$songs = Song::where('song_primary_artist_id', $artist_id)->orderBy('song_title')->get();
			$artist = Artist::find($artist_id);
		} else {
			$songs = Song::orderBy('song_title')->get();
			$artist = new Artist;
		}

		$method_variables = array(
			'songs' => $songs,
			'artist' => $artist,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('song.index', $data);
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$song = new Song;

		$artist_id = Request::get('artist');

		if (!empty($artist_id)) {
			$song->song_primary_artist_id = $artist_id;
			$song->artist = Artist::find($artist_id);
		}

		$artists = $this->build_artist_options();

		$method_variables = array(
			'song' => $song,
			'artists' => $artists,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('song.create', $data);
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$song = new Song;

		$fields = $song->getFillable();

		foreach ($fields as $field) {
			$song->{$field} = Request::get($field);
		}

		$result = $song->save();

		if ($result !== false) {
			return Redirect::route('song.show', $song->song_id)->with('message', 'Your changes were saved.');
		} else {
			return Redirect::route('song.index', $song->song_primary_artist_id )->with('error', 'Your changes were not saved.');
		}
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$method_variables = array(
			'song' => $id,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('song.show', $data);
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$artists = $this->build_artist_options();

		$method_variables = array(
			'song' => $id,
			'artists' => $artists,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('song.edit', $data);
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$fields = $id->getFillable();

		foreach ($fields as $field) {
			$id->{$field} = Request::get($field);
		}

		$result = $id->save();

		if ($result !== false) {
			return Redirect::route('song.show', $id->song_id)->with('message', 'Your changes were saved.');
		} else {
			return Redirect::route('song.index', array('artist' => $id->song_primary_artist_id) )->with('error', 'Your changes were not saved.');
		}
	}

	public function delete($id) {

		$method_variables = array(
			'song' => $id,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('song.delete', $data);
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$confirm = (boolean) Request::get('confirm');
		$song_title = $id->song_title;
		$artist_id = $id->song_primary_artist_id;

		if ($confirm === true) {
			// Remove recordings.
			$id->recordings()->delete();

			// Remove tracks.
			$id->tracks()->delete();

			// Remove song.
			$id->delete();
			return Redirect::route('song.index', array('artist' => $artist_id  ))->with('message', $song_title . ' was deleted.');
		} else {
			return Redirect::route('song.show', $id->song_id)->with('error', $song_title . ' was not deleted.');
		}

	}

	private function build_artist_options() {
		$artists = Artist::orderBy('artist_display_name')->pluck('artist_display_name', 'artist_id');
		$artists = array(0 => '&nbsp;') + $artists->toArray();

		return $artists;
	}

}

resources/views/song/_form.blade.php
@extends('layout')

@section('content')

<div class="form-group">
	{!! Form::label( 'song_primary_artist_id', 'Primary artist:', array( 'class' => 'col-sm-2' ) ) !!}
	<div class="col-sm-10">
		{!! Form::select( 'song_primary_artist_id', $artists, $song->song_primary_artist_id, array( 'class' => 'form-control' ) ) !!}
	</div>
</div>

<div class="form-group">
	{!! Form::label( 'song_title', 'Song title:', array( 'class' => 'col-sm-2' ) ) !!}
	<div class="col-sm-10">
		{!! Form::text( 'song_title', $song->song_title, array( 'class' => 'form-control' ) ) !!}
	</div>
</div>

<div class="form-group">
	{!! Form::label( 'song_alias', 'Alias:', array( 'class' => 'col-sm-2' ) ) !!}
	<div class="col-sm-10">
		{!! Form::text( 'song_alias', $song->song_alias, array( 'class' => 'form-control' ) ) !!}
	</div>
</div>

<div class="form-group">
	{!! Form::label( 'song_author', 'Author:', array( 'class' => 'col-sm-2' ) ) !!}
	<div class="col-sm-10">
		{!! Form::text( 'song_author', $song->song_author, array( 'class' => 'form-control' ) ) !!}
	</div>
</div>

<div class="form-group">
	{!! Form::label( 'song_influences', 'Influences:', array( 'class' => 'col-sm-2' ) ) !!}
	<div class="col-sm-10">
		{!! Form::text( 'song_influences', $song->song_influences, array( 'class' => 'form-control' ) ) !!}
	</div>
</div>

<div class="form-group">
	{!! Form::label( 'song_style', 'Style:', array( 'class' => 'col-sm-2' ) ) !!}
	<div class="col-sm-10">
		{!! Form::text( 'song_style', $song->song_style, array( 'class' => 'form-control' ) ) !!}
	</div>
</div>

<div class="form-group">
	{!! Form::label( 'song_written_date', 'Date written:', array( 'class' => 'col-sm-2' ) ) !!}
	<div class="col-sm-10">
		{!! Form::text( 'song_written_date', $song->song_written_date, array( 'class' => 'form-control' ) ) !!}
	</div>
</div>

<div class="form-group">
	{!! Form::label( 'song_revised_date', 'Date revised:', array( 'class' => 'col-sm-2' ) ) !!}
	<div class="col-sm-10">
		{!! Form::text( 'song_revised_date', $song->song_revised_date, array( 'class' => 'form-control' ) ) !!}
	</div>
</div>

<div class="form-group">
	{!! Form::label( 'song_recorded_date', 'Date recorded:', array( 'class' => 'col-sm-2' ) ) !!}
	<div class="col-sm-10">
		{!! Form::text( 'song_recorded_date', $song->song_recorded_date, array( 'class' => 'form-control' ) ) !!}
	</div>
</div>

<div class="form-group">
	{!! Form::label( 'song_lyrics', 'Lyrics:', array( 'class' => 'col-sm-2' ) ) !!}
	<div class="col-sm-10">
		{!! Form::textarea( 'song_lyrics', $song->song_lyrics, array( 'class' => 'form-control' ) ) !!}
	</div>
</div>

<div class="form-group">
	{!! Form::label( 'song_abstract', 'Abstract:', array( 'class' => 'col-sm-2' ) ) !!}
	<div class="col-sm-10">
		{!! Form::textarea( 'song_abstract', $song->song_abstract, array( 'class' => 'form-control' ) ) !!}
	</div>
</div>

<div class="col-sm-offset-2 col-sm-10">
    <ul class="list-inline">
        <li>{!! Form::submit( 'Save', array( 'class' => 'btn btn-primary' ) ) !!}</li>
        <li>
            @if (!empty( $song->song_id))
                <a href="{{ route( 'song.show', $song->song_id ) }}" class="btn btn-default">Cancel</a>
            @elseif (!empty($song->song_primary_artist_id))
                <a href="{{ route( 'artist.show', $song->song_primary_artist_id ) }}" class="btn btn-default">Cancel</a>
            @else
                <a href="{{ route( 'song.index' ) }}" class="btn btn-default">Cancel</a>
            @endif
        </li>
    </ul>
</div>

<script type="text/javascript">
	(function ($) {
		$('#song_title').keyup(function () {
			var alias = this.value.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9\-]+/g, '').replace(/(^-|-$)/, '');
			$('#song_alias').val(alias);
		});
		$('#song_primary_artist_id').chosen();
	})(jQuery);
</script>

@stop

resources/views/song/create.blade.php
@extends('song._form')

@section('page_title')
@if (!empty($song->artist->artist_display_name))
 &raquo; {{ $song->artist->artist_display_name }}
@endif
 &raquo; Add
@stop

@section('section_header')
<hgroup>
	<h2>
		@if (!empty($song->artist->artist_display_name))
		{{ $song->artist->artist_display_name }}
		@else
		Observant Records
		@endif
	</h2>
</hgroup>
@stop

@section('section_label')
<h3>Add a new song</h3>
@stop

@section('content')
{!! Form::model( $song, array( 'route' => 'song.store', 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'post' ) ) !!}
@parent
{!! Form::close() !!}
@stop

resources/views/song/delete.blade.php
@extends('layout')

@section('page_title')
 &raquo; {{ $song->artist->artist_display_name }}
 &raquo; {{ $song->song_title }}
 &raquo; Delete
@stop

@section('section_header')
<hgroup>
	<h2>
		{{ $song->artist->artist_display_name }}
		<small>{{ $song->song_title }}</small>
	</h2>
</hgroup>
@stop

@section('section_label')
<h3>Delete</h3>
@stop

@section('content')

<p>
	You are about to delete <strong>{{ $song->song_title }}</strong> from the database.
</p>

<p>
	Are you sure you want to do this?
</p>

{!! Form::model( $song, array( 'route' => array( 'song.destroy', $song->song_id), 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'delete' ) ) !!}

<div class="form-group">
	<div class="col-sm-12">
		<div class="radio">
			<label>
				{!! Form::radio('confirm', '1') !!} Yes, I want to delete {{ $song->song_title }}.
			</label>
		</div>
		<div class="radio">
			<label>
				{!! Form::radio('confirm', '0') !!} No, I don't want to delete {{ $song->song_title }}.
			</label>
		</div>
	</div>
</div>

<div class="form-group">
	<div class="col-sm-12">
		{!! Form::submit('Confirm', array( 'class' => 'btn btn-danger' ) ) !!}
	</div>
</div>


{!! Form::close() !!}

@stop

resources/views/song/edit.blade.php
@extends('song._form')

@section('page_title')
 &raquo; {{ $song->artist->artist_display_name }}
 &raquo; {{ $song->song_title }}
 &raquo; Edit
@stop

@section('section_header')
<hgroup>
	<h2>
		{{ $song->artist->artist_display_name }}
		<small>{{ $song->song_title }}</small>
	</h2>
</hgroup>
@stop

@section('section_label')
<h3>Edit</h3>
@stop

@section('content')
{!! Form::model( $song, array( 'route' => array('song.update', $song->song_id), 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'put' ) ) !!}
@parent
{!! Form::close() !!}
@stop

resources/views/song/index.blade.php
@extends('layout')

@section('page_title')
@if (!empty($artist->artist_display_name))
 &raquo; {{ $artist->artist_display_name }}
@endif
 &raquo; Songs
@stop

@section('section_header')
<h2>
	@if (!empty($artist->artist_display_name))
	&raquo; {{ $artist->artist_display_name }}
	@else
	Observant Records
	@endif
</h2>
@stop

@section('section_label')
<h3>
	Songs
	<small>Browse</small>
</h3>
@stop

@section('content')

<p>
	@if (!empty($artist->artist_id))
	<a href="{{ route('song.create', array( 'artist' => $artist->artist_id ) ) }}" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Add a song</a>
	@else
	<a href="{{ route('song.create') }}" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Add a song</a>
	@endif
</p>

@if (!empty($songs))
<ul class="two-column-bubble-list">
	@foreach ($songs as $song)
	<li @if (!empty($rsSong->song_author)) class="cover" @endif>
	<div>
		<a href="{{ route('song.edit', $song->song_id ) }}" title="[Edit]"><span class="glyphicon glyphicon-pencil"></span></a>
		<a href="{{ route('song.delete', $song->song_id ) }}" title="[Delete]"><span class="glyphicon glyphicon-remove"></span></a>
		<a href="{{ route('song.show', $song->song_id ) }}">{{ $song->song_title }}</a>
	</div>
	</li>
	@endforeach
</ul>
@else
<p>
	This artist has no songs. Please add one.
</p>
@endif

@stop

resources/views/song/show.blade.php
@extends('layout')

@section('page_title')
 &raquo; {{ $song->artist->artist_display_name }}
 &raquo; {{ $song->song_title }}
@stop

@section('section_header')
<hgroup>
	<h2>
		{{ $song->artist->artist_display_name }}
		<small>{{ $song->song_title }}</small>
	</h2>
</hgroup>
@stop

@section('section_label')
<h3>Song information</h3>
@stop

@section('content')

<p>
	<a href="{{ route('song.edit', $song->song_id) }}" class="btn btn-primary">Edit</a>
	<a href="{{ route('song.delete', $song->song_id) }}" class="btn btn-warning">Delete</a>
</p>

<ul class="two-column-bubble-list">
	<li>
		<div>
			<label>Title</label> {{ $song->song_title }}
		</div>
	</li>
	<li>
		<div>
			<label>Alias</label> {{ $song->song_alias }}
		</div>
	</li>
	@if (!empty($rsSong->song_author))
	<li>
		<div>
			<label>Author</label> {{ $song->song_author }}
		</div>
	</li>
	@endif
	<li>
		<div>
			<label>Influences</label> {{ $song->song_influences }}
		</div>
	</li>
	<li>
		<div>
			<label>Style</label> {{ $song->song_style }}
		</div>
	</li>
	<li>
		<div>
			<label>Date written</label> {{ $song->song_written_date }}
		</div>
	</li>
	<li>
		<div>
			<label>Date revised</label> {{ $song->song_revised_date }}
		</div>
	</li>
	<li>
		<div>
			<label>Date recorded</label> {{ $song->song_recorded_date }}
		</div>
	</li>
</ul>

<h4>Recordings</h4>

@if (count($song->recordings) > 0)
<ol class="track-list">
	@foreach ($song->recordings as $recording)
	<li>
		<div>
			<a href="{{ route( 'recording.edit', $recording->recording_id ) }}"><span class="glyphicon glyphicon-pencil"></span></a>
			<a href="{{ route( 'recording.delete', $recording->recording_id ) }}"><span class="glyphicon glyphicon-remove"></span></a>
			<a href="{{ route( 'recording.show', $recording->recording_id ) }}">@if (empty($recording->recording_isrc_num)) (ISRC TBD) @else {{ $recording->recording_isrc_num }} @endif</a>
		</div>
	</li>
	@endforeach
</ol>
@else
<p>No recordings have been made.</p>
@endif

<h4>Tracks</h4>

@if (count($song->tracks) > 0)
<ol class="track-list">
	@foreach ($song->tracks as $track)
	<li>
		<div>
			<a href="{{ route( 'track.edit', $track->track_id ) }}"><span class="glyphicon glyphicon-pencil"></span></a>
			<a href="{{ route( 'track.delete', $track->track_id ) }}"><span class="glyphicon glyphicon-remove"></span></a>
			<em><a href="{{ route( 'track.show', $track->track_id ) }}">{{ $track->release->release_alias }}</a></em>
		</div>
	</li>
	@endforeach
</ol>
@else
<p>No tracks have been created.</p>
@endif

@if (!empty($rsSong->song_lyrics))
<h4>Lyrics</h4>

{{ $song->song_lyrics }}

@endif

@if (!empty($rsSong->song_abstract))
<h4>Abstract</h4>

{{ $song->song_abstract }}
@endif
@stop