routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::group(['middleware' => 'auth'], function () {
	Route::get('/', array( 'as' => 'index', 'uses' => 'ArtistController@index' ) );
	Route::get('/home', array( 'as' => 'home', 'uses' => 'ArtistController@index' ) );

// Artist
	Route::model('artist', 'App\Models\Artist');
	Route::resource('artist', 'ArtistController');
	Route::get( '/artist/{artist}/delete', array( 'as' => 'artist.delete', 'uses' => 'ArtistController@delete' ) );

// Album
	Route::model('album', 'App\Models\Album');
	Route::resource('album', 'AlbumController');
	Route::get( '/album/{album}/delete', array( 'as' => 'album.delete', 'uses' => 'AlbumController@delete' ) );
	Route::post( '/album/save-order', array( 'as' => 'album.save-order', 'uses' => 'AlbumController@save_order' ) );

// Release
	Route::model('release', 'App\Models\Release');
	Route::resource('release', 'ReleaseController');
	Route::get( '/release/{release}/delete', array( 'as' => 'release.delete', 'uses' => 'ReleaseController@delete' ) );
	Route::get( '/release/{release}/export-id3', array( 'as' => 'release.export-id3', 'uses' => 'ReleaseController@export_id3' ) );
	Route::post( '/release/generate-catalog-num', array( 'as' => 'release.catalog-num', 'uses' => 'ReleaseController@generate_catalog_num' ) );

// Tracks
	Route::model('track', 'App\Models\Track');
	Route::get( '/track/{track}/delete', array( 'as' => 'track.delete', 'uses' => 'TrackController@delete' ) );
	Route::post( '/track/save-order', array( 'as' => 'track.save-order', 'uses' => 'TrackController@save_order' ) );
	Route::resource('track', 'TrackController');

// Audio
	Route::model('audio', 'App\Models\Audio');
	Route::get( '/audio/{audio}/delete/', array( 'as' => 'audio.delete', 'uses' => 'AudioController@delete' ) );
	Route::resource('audio', 'AudioController');

// Ecommerce
	Route::model('ecommerce', 'App\Models\Ecommerce');
	Route::get( '/ecommerce/{ecommerce}/delete', array( 'as' => 'ecommerce.delete', 'uses' => 'EcommerceController@delete' ) );
	Route::post( '/ecommerce/save-order', array( 'as' => 'ecommerce.save-order', 'uses' => 'EcommerceController@save_order' ) );
	Route::resource('ecommerce', 'EcommerceController');

// Songs
	Route::model('song', 'App\Models\Song');
	Route::get( '/song/{song}/delete', array( 'as' => 'song.delete', 'uses' => 'SongController@delete' ) );
	Route::get( '/song/{song}/lyrics', array( 'as' => 'song.lyrics', 'uses' => 'SongController@lyrics' ) );
	Route::resource('song', 'SongController');

// Recordings
	Route::model('recording', 'App\Models\Recording');
	Route::get( '/recording/{recording}/delete', array( 'as' => 'recording.delete', 'uses' => 'RecordingController@delete' ) );
	Route::post( '/recording/generate-isrc', array( 'as' => 'recording.isrc', 'uses' => 'RecordingController@generate_isrc' ) );
	Route::resource('recording', 'RecordingController');

// Profile
	Route::model('user', 'App\Models\User');
	Route::resource('user', 'UserController');
	Route::get( '/user/{user}/delete', array( 'as' => 'user.delete', 'uses' => 'UserController@delete' ) );
});

Auth::routes();

app/Models/Recording.php
<?php
/**
 * Created by PhpStorm.
 * User: gbueno
 * Date: 5/28/14
 * Time: 2:59 PM
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Recording extends Model {

	protected $table = 'ep4_recordings';
	protected $primaryKey = 'recording_id';
	protected $softDelete = true;
	protected $fillable = array(
		'recording_song_id',
		'recording_artist_id',
		'recording_isrc_num',
	);
	protected $guarded = array(
		'recording_id',
		'recording_deleted',
	);

	public function song() {
		return $this->belongsTo('App\Models\Song', 'recording_song_id', 'song_id');
	}

	public function artist() {
		return $this->belongsTo('App\Models\Artist', 'recording_artist_id', 'artist_id');
	}

	public function isrc() {
		return $this->hasOne('App\Models\RecordingISRC', 'isrc_code', 'recording_isrc_num');
	}

	public function audio() {
		return $this->hasMany('App\Models\Audio', 'audio_recording_id', 'recording_id');
	}

} 

app/Http/Controllers/RecordingController.php
<?php

namespace App\Http\Controllers;

use App\Models\Artist;
use App\Models\Song;
use App\Models\Recording;
use App\Models\RecordingISRC;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Request;
use Illuminate\Support\Facades\View;

class RecordingController extends Controller {

	private $layout_variables = array();

	public function __construct() {

	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$artist_id = Request::get('artist');

		if (!empty($artist_id)) {
			$artist = Artist::find($artist_id);
			$recordings = Recording::where('recording_artist_id', $artist_id)->orderBy('recording_isrc_num')->get();
		} else {
			$artist = new Artist;
			$recordings = Recording::orderBy('recording_isrc_num')->get();
		}
		$recordings->load('song');

		$recording_list = $recordings->pluck('recording_isrc_num', 'recording_id');
		foreach ($recording_list as $r => $recording) {
			$song_title = (!empty($recordings->find($r)->song->song_title)) ? $recordings->find($r)->song->song_title : 'TBD';
			$recording_list[$r] = $song_title . ' ('. $recording . ')';
		}
		$recording_list = array(0 => '&nbsp;') + $recording_list->toArray();

		$method_variables = array(
			'recordings' => $recording_list,
			'artist' => $artist,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('recording.index', $data);
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$recording = new Recording;

		$artist_id = Request::get('artist');
		if (!empty($artist_id)) {
			$recording->recording_artist_id = $artist_id;
			$recording->artist = Artist::find($artist_id);
		}

		$artists = Artist::orderBy('artist_last_name')->pluck('artist_display_name', 'artist_id');
		$artists = array(0 => '&nbsp;') + $artists->toArray();

		$songs = Song::orderBy('song_title')->pluck('song_title', 'song_id');
		$songs = array(0 => '&nbsp;') + $songs->toArray();

		$method_variables = array(
			'recording' => $recording,
			'artists' => $artists,
			'songs' => $songs,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('recording.create', $data);
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$recording = new Recording;

		$fields = $recording->getFillable();

		foreach ($fields as $field) {
			$recording->{$field} = Request::get($field);
		}

		$result = $recording->save();

		if ($result !== false) {
			$recording_isrc_num = Request::get('recording_isrc_num');
            $isrc = RecordingISRC::where('isrc_code', $recording_isrc_num)->first();
			if (!empty($isrc)) {
				$isrc->isrc_recording_id = $recording->recording_id;
				$isrc->save();
			} else {
                $isrc = new RecordingISRC();

                $isrc->isrc_code = $recording_isrc_num;
                $isrc->isrc_recording_id = $recording->recording_id;
                $isrc->save();
            }
			return Redirect::route('recording.show', $recording->recording_id)->with('message', 'Your changes were saved.');
		} else {
			return Redirect::route('recording.index', array('artist' => $recording->recording_artist_id))->with('error', 'Your changes were not saved.');
		}
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$method_variables = array(
			'recording' => $id,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('recording.show', $data);
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$artists = Artist::orderBy('artist_last_name')->pluck('artist_display_name', 'artist_id');
		$artists = array(0 => '&nbsp;') + $artists->toArray();

		$songs = Song::orderBy('song_title')->pluck('song_title', 'song_id');
		$songs = array(0 => '&nbsp;') + $songs->toArray();

		$method_variables = array(
			'recording' => $id,
			'artists' => $artists,
			'songs' => $songs,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('recording.edit', $data);
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$fields = $id->getFillable();

		foreach ($fields as $field) {
			$id->{$field} = Request::get($field);
		}

		$recording_isrc_num = Request::get('recording_isrc_num');
		if (!empty($recording_isrc_num)) {
			$isrc = RecordingISRC::where('isrc_code', $recording_isrc_num)->first();
			$isrc->isrc_recording_id = $id->recording_id;
			$isrc->save();
		}

		$result = $id->save();

		if ($result !== false) {
			return Redirect::route('recording.show', $id->recording_id)->with('message', 'Your changes were saved.');
		} else {
			return Redirect::route('recording.index', array('artist' => $id->recording_artist_id))->with('error', 'Your changes were not saved.');
		}
	}


	public function delete($id) {

		$method_variables = array(
			'recording' => $id,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('recording.delete', $data);
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$confirm = (boolean) Request::get('confirm');
		$recording_isrc_num = $id->recording_isrc_num;

		if ($confirm === true) {
			// Remove audio.
			$id->audio()->delete();

			// Remove ISRC.
			$id->isrc()->delete();

			// Remove recording.
			$id->delete();
			return Redirect::route('recording.index', array('artist' => $id->recording_artist_id) )->with('message', $recording_isrc_num . ' was deleted.');
		} else {
			return Redirect::route('recording.show', $id->recording_id )->with('error', $recording_isrc_num . ' was not deleted.');
		}
	}

	public function generate_isrc() {
		$isrc = new RecordingISRC;
		$recording_isrc_code = (object) array('isrc_code' => $isrc->generate_code());
		echo json_encode($recording_isrc_code);
	}

}

resources/views/recording/_form.blade.php
@extends('layout')

@section('content')

<div class="form-group">
	<div class="form-group">
		{!! Form::label('recording_artist_id', 'Artist:', array( 'class' => 'col-sm-2' ) ) !!}
		<div class="col-sm-10">
			{!! Form::select( 'recording_artist_id', $artists, $recording->recording_artist_id, array( 'class' => 'form-control' ) ) !!}
		</div>
	</div>

	<div class="form-group">
		{!! Form::label('recording_song_id', 'Song:', array( 'class' => 'col-sm-2' ) ) !!}
		<div class="col-sm-10">
			{!! Form::select( 'recording_song_id', $songs, $recording->recording_song_id, array( 'class' => 'form-control' ) ) !!}
		</div>
	</div>

	<div class="form-group">
		{!! Form::label('recording_song_id', 'ISRC No.:', array( 'class' => 'col-sm-2' ) ) !!}
		<div class="col-sm-10">
			@if (!empty($recording->recording_isrc_num))
			{{ $recording->recording_isrc_num }}
			{!! Form::hidden( 'recording_isrc_num', $recording->recording_isrc_num, array( 'id' => 'recording_isrc_num' ) ) !!}
			@else
			{!! Form::text( '_display_recording_isrc_num', null, array('id' => '_display_recording_isrc_num') ) !!}
			{!! Form::hidden( 'recording_isrc_num', null, array( 'id' => 'recording_isrc_num' ) ) !!}
			{!! Form::hidden( 'recording_isrc_code', null, array( 'id' => 'recording_isrc_code' ) ) !!}
			{!! Form::button( 'Generate', array('id' => 'generate_custom_isrc', 'class' => 'btn btn-default') ) !!}
			{!! Form::button( 'Clear', array('id' => 'clear_custom_isrc', 'class' => 'btn btn-default') ) !!}
			@endif
		</div>
	</div>

	<div class="col-sm-offset-2 col-sm-10">
        <ul class="list-inline">
            <li>{!! Form::submit( 'Save', array( 'class' => 'btn btn-primary' ) ) !!}</li>
            <li>
                @if (!empty( $recording->recording_id))
                    <a href="{{ route( 'recording.show', $recording->recording_id ) }}" class="btn btn-default">Cancel</a>
                @elseif (!empty($recording->recording_artist_id))
                    <a href="{{ route( 'artist.show', $recording->recording_artist_id ) }}" class="btn btn-default">Cancel</a>
                @else
                    <a href="{{ route( 'recording.index' ) }}" class="btn btn-default">Cancel</a>
                @endif
            </li>
        </ul>
	</div>
</div>

<script type="text/javascript">
	(function ($) {
		var Recording_Edit = {
			generate_catalog_num: function () {
				var _token = $('input[name=_token]').val();
				var data = {
					'_token': _token
				}
				var url = '/recording/generate-isrc';
				$.post(url, data, function (response) {
					var result = $.parseJSON(response);
					$('#recording_isrc_code').val(result.isrc_code);
					$('#recording_isrc_num').val(result.isrc_code);
					$('#_display_recording_isrc_num').val(result.isrc_code);
				}).error(function (xmlreq, status, error_text) {
					alert(error_text);
				});
			}
		};
		$('#generate_custom_isrc').click(function () {
			Recording_Edit.generate_catalog_num();
		});
		$('#recording_artist_id').chosen();
		$('#recording_song_id').chosen();

		$('#clear_custom_isrc').click(function () {
			$('#_display_recording_isrc_num').val('');
			$('#recording_isrc_num').val('');
			$('#recording_isrc_code').val('');
		});

		$('#_display_recording_isrc_num').blur(function () {
			$('#recording_isrc_num').val($('#_display_recording_isrc_num').val());
			$('#recording_isrc_code').val($('#_display_recording_isrc_num').val());
		});
	})(jQuery);
</script>

@stop

resources/views/recording/create.blade.php
@extends('recording._form')

@section('page_title')
@if (!empty($recording->artist->artist_display_name))
 &raquo; {{ $recording->artist->artist_display_name }}
@endif
 &raquo; Add a new recording
@stop

@section('section_header')
<h2>
	@if (!empty($recording->artist->artist_display_name))
	{{ $recording->artist->artist_display_name }}
	@else
	Observant Records
	@endif
</h2>
@stop

@section('section_label')
<h3>Add a new recording</h3>
@stop

@section('content')
{!! Form::model( $recording, array( 'route' => 'recording.store', 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'post' ) ) !!}
@parent
{!! Form::close() !!}
@stop

resources/views/recording/delete.blade.php
@extends('layout')

@section('page_title')
 &raquo; {{ $recording->artist->artist_display_name }}
@if (!empty($recording->recording_isrc_num))
 &raquo; {{ $recording->recording_isrc_num }}
@endif
 &raquo; Edit
@stop

@section('section_header')
<h2>
	{{ $recording->artist->artist_display_name }}
	@if (!empty($recording->song->song_title))
	<small>{{ $recording->song->song_title }}</small>
	@endif
</h2>
@stop

@section('section_label')
<h3>
	Delete
	@if (!empty($recording->recording_isrc_num))
	<small>{{ $recording->recording_isrc_num }}</small>
	@endif
</h3>
@stop

@section('content')

<p>
	You are about to delete <strong>{{ $recording->recording_isrc_num  }}</strong> from the database.
</p>

<p>
	Are you sure you want to do this?
</p>

{!! Form::model( $recording, array( 'route' => array( 'recording.destroy', $recording->recording_id), 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'delete' ) ) !!}

<div class="form-group">
	<div class="col-sm-12">
		<div class="radio">
			<label>
				{!! Form::radio('confirm', '1')  !!} Yes, I want to delete {{ $recording->recording_isrc_num }}.
			</label>
		</div>
		<div class="radio">
			<label>
				{!! Form::radio('confirm', '0')  !!} No, I don't want to delete {{ $recording->recording_isrc_num }}.
			</label>
		</div>
	</div>
</div>

<div class="form-group">
	<div class="col-sm-12">
		{!! Form::submit('Confirm', array( 'class' => 'btn btn-default' )) !!}
	</div>
</div>

{!! Form::close() !!}

@stop

resources/views/recording/edit.blade.php
@extends('recording._form')

@section('page_title')
 &raquo; {{ $recording->artist->artist_display_name }}
@if (!empty($recording->recording_isrc_num))
 &raquo; {{ $recording->recording_isrc_num }}
@endif
 &raquo; Edit
@stop

@section('section_header')
<h2>
	{{ $recording->artist->artist_display_name }}
	@if (!empty($recording->song->song_title))
	<small>{{ $recording->song->song_title }}</small>
	@endif
</h2>
@stop

@section('section_label')
<h3>
	Edit
	@if (!empty($recording->recording_isrc_num))
	<small>{{ $recording->recording_isrc_num }}</small>
	@endif
</h3>
@stop

@section('content')
{!! Form::model( $recording, array( 'route' => array('recording.update', $recording->recording_id), 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'put' ) ) !!}
@parent
{!! Form::close() !!}
@stop

resources/views/recording/index.blade.php
@extends('layout')

@section('page_title')
@if (!empty($artist->artist_display_name))
&raquo; {{ $artist->artist_display_name }}
@endif
 &raquo; Recordings &raquo; Browse
@stop

@section('section_header')
<h2>
	@if (!empty($artist->artist_display_name))
	{{ $artist->artist_display_name }}
	@else
	Observant Records
	@endif
</h2>
@stop

@section('section_label')
<h3>
	Recordings
	<small>Browse</small>
</h3>
@stop

@section('content')

<p>
	@if (!empty($artist->artist_id))
	<a href="{{ route('recording.create', array( 'artist' => $artist->artist_id )) }}" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Add a recording</a>
	@else
	<a href="{{ route('recording.create') }}" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Add a recording</a>
	@endif
</p>

@if (count($recordings) > 0)

{!! Form::open(array('id' => 'recording-id', 'class' => 'form-horizontal')) !!}

<div class="form-group">
	<div class="col-sm-12">
		{!! Form::select( 'recording_id', $recordings, null, array('class' => 'form-control', 'id' => 'recording_id') ) !!}
	</div>
</div>

<div class="form-group">
	<div class="col-sm-2">
		{!! Form::button('View', array( 'class' => 'btn btn-default', 'id' => 'select-recording' ) ); !!}
	</div>
</div>

{!! Form::close() !!}

<script type="text/javascript">
	(function ($) {
		$(function () {
			$('#recording_id').chosen();

			var Recording_List = {
				select_recording: function (recording_id) {
					var url = '/recording/' + recording_id;
					location.href = url;
				}
			};

			$('#recording_id').change(function () {
				Recording_List.select_recording(this.value);
			});
			$('#select-recording').click(function () {
				Recording_List.select_recording($('#recording_id').val());
			});
		});
	})(jQuery);
</script>

@endif

@stop

resources/views/recording/show.blade.php
@extends('layout')

@section('page_title')
 &raquo; {{ $recording->artist->artist_display_name }}
@if (!empty($recording->recording_isrc_num))
 &raquo; {{ $recording->recording_isrc_num }}
@endif
@stop

@section('section_header')
<hgroup>
	<h2>
		{{ $recording->artist->artist_display_name }}
		<small>{{ $recording->song->song_title }}</small>
	</h2>
</hgroup>
@stop

@section('section_label')
<h3>
	Recording info
	@if (!empty($recording->recording_isrc_num))
	<small>{{ $recording->recording_isrc_num }}</small>
	@endif
</h3>
@stop

@section('content')

<p>
	<a href="{{ route( 'recording.edit', $recording->recording_id ) }}" class="btn btn-primary">Edit</a>
	<a href="{{ route( 'recording.delete', $recording->recording_id ) }}" class="btn btn-warning">Delete</a>
</p>

<ul class="two-column-bubble-list">
	<li>
		<div>
			<label>Song</label> {{ $recording->song->song_title }}
		</div>
	</li>
	<li>
		<div>
			<label>ISRC</label>
			@if (empty($recording->recording_isrc_num))
			Not set
			@else
			{{ $recording->recording_isrc_num }}
			@endif
		</div>
	</li>
</ul>

<h3>Audio files</h3>

<p>
	<a href="{{ route( 'audio.create', array('recording' => $recording->recording_id) ) }}" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Add an audio file</a>
</p>

@if (count($recording->audio) > 0)
<ol class="disc-list">
	@foreach ($recording->audio as $audio)
	<li>
		<div>
			<ul class="list-inline">
				<li><a href="{{ route( 'audio.edit', $audio->audio_id ) }}" title="[Edit audio]"><span class="glyphicon glyphicon-pencil"></span></a></li>
				<li><a href="{{ route( 'audio.delete', $audio->audio_id ) }}" title="[Remove audio]"><span class="glyphicon glyphicon-remove"></span></a></li>
				<li><a href="{{ route( 'audio.show', $audio->audio_id ) }}" title="[{{ $audio->audio_file_server }}{{ $audio->audio_file_path }}/{{ $audio->audio_file_name }}]">{{ $audio->audio_file_name }}</a></li>
			</ul>
		</div>
	</li>
	@endforeach
</ol>
@else
<p>
	This recording has no audio files associated with it.
</p>
@endif

@stop